/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import com.mysql.cj.protocol.Resultset;
//import com.sun.jdi.connect.spi.Connection;
import com.mysql.cj.protocol.Resultset;
import java.beans.Statement;
import java.sql.*;
import model.DatabaseCon;

/**
 *
 * @author HP
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
    
    public VHome() {
        initComponents();
        setCount();
    }
    
    public void setCount(){
      
        try {
            Connection con =DatabaseCon.createDBConnection();
            String query = "SELECT count(*) as rowcount from book";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            //resultSet.last();
            //resultSet.getRow();
            //lbl_books_no.setText(Integer.toString(resultSet.getRow()));
            
            if (resultSet.next()) {
            int rowCount = resultSet.getInt("rowCount");
            lbl_books_no.setText(Integer.toString(rowCount));
        }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panal_view_return = new javax.swing.JPanel();
        lbl_view_return = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panal_managebook = new javax.swing.JPanel();
        lbl_manage_book = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panal_manage_student = new javax.swing.JPanel();
        lbl_manage_students = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        panal_issue = new javax.swing.JPanel();
        lbl_issue = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        panal_return = new javax.swing.JPanel();
        lbl_return = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        panal_report = new javax.swing.JPanel();
        lbl_report = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        panal_view_issue = new javax.swing.JPanel();
        lbl_view_issue = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        panal_logout = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jPanel77 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jPanel78 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jPanel79 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jPanel80 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        lbl_student = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel83 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        lbl_books_no = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jPanel84 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        lbl_no_bookissue = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jPanel85 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        lbl_no_of_books_toreturn = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menu-30.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, 3, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1170, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel5.setText("    Home Page");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel6.setText("    Home Page");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel8.setBackground(new java.awt.Color(204, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel7.setText("    Home Page");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel13.setBackground(new java.awt.Color(204, 0, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel12.setText("    Home Page");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel14.setBackground(new java.awt.Color(204, 0, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel13.setText("    Home Page");
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel15.setBackground(new java.awt.Color(204, 0, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel14.setText("    Home Page");
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel16.setBackground(new java.awt.Color(204, 0, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel15.setText("    Home Page");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        panal_view_return.setBackground(new java.awt.Color(0, 0, 0));
        panal_view_return.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_view_return.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_view_return.setForeground(new java.awt.Color(255, 255, 255));
        lbl_view_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-view-24.png"))); // NOI18N
        lbl_view_return.setText("View Returned Book");
        panal_view_return.add(lbl_view_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 220, 50));

        jPanel66.setBackground(new java.awt.Color(204, 0, 0));
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel65.setText("    Home Page");
        jPanel66.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_view_return.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel67.setBackground(new java.awt.Color(204, 0, 0));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel66.setText("    Home Page");
        jPanel67.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel68.setBackground(new java.awt.Color(204, 0, 0));
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel67.setText("    Home Page");
        jPanel68.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel67.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_view_return.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel69.setBackground(new java.awt.Color(204, 0, 0));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel68.setText("    Home Page");
        jPanel69.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel70.setBackground(new java.awt.Color(204, 0, 0));
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel69.setText("    Home Page");
        jPanel70.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel69.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel71.setBackground(new java.awt.Color(204, 0, 0));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel70.setText("    Home Page");
        jPanel71.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel72.setBackground(new java.awt.Color(204, 0, 0));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel71.setText("    Home Page");
        jPanel72.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel71.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel69.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_view_return.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel5.add(panal_view_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        jPanel9.setBackground(new java.awt.Color(204, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel8.setText("    Home Page");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel10.setBackground(new java.awt.Color(204, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel9.setText("    Home Page");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel11.setBackground(new java.awt.Color(204, 0, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel10.setText("    Home Page");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel12.setBackground(new java.awt.Color(204, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel11.setText("    Home Page");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_managebook.setBackground(new java.awt.Color(0, 0, 0));
        panal_managebook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manage_book.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_manage_book.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manage_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-books-30.png"))); // NOI18N
        lbl_manage_book.setText("Manage Books");
        lbl_manage_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manage_bookMouseClicked(evt);
            }
        });
        panal_managebook.add(lbl_manage_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 230, 50));

        jPanel18.setBackground(new java.awt.Color(204, 0, 0));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel17.setText("    Home Page");
        jPanel18.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_managebook.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel19.setBackground(new java.awt.Color(204, 0, 0));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel18.setText("    Home Page");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel20.setBackground(new java.awt.Color(204, 0, 0));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel19.setText("    Home Page");
        jPanel20.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_managebook.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel21.setBackground(new java.awt.Color(204, 0, 0));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel20.setText("    Home Page");
        jPanel21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel22.setBackground(new java.awt.Color(204, 0, 0));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel21.setText("    Home Page");
        jPanel22.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel23.setBackground(new java.awt.Color(204, 0, 0));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel22.setText("    Home Page");
        jPanel23.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel24.setBackground(new java.awt.Color(204, 0, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel23.setText("    Home Page");
        jPanel24.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel21.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_managebook.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_managebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        panal_manage_student.setBackground(new java.awt.Color(0, 0, 0));
        panal_manage_student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manage_students.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_manage_students.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manage_students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-online-group-studying-30.png"))); // NOI18N
        lbl_manage_students.setText("Manage Students");
        lbl_manage_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manage_studentsMouseClicked(evt);
            }
        });
        panal_manage_student.add(lbl_manage_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 240, 50));

        jPanel26.setBackground(new java.awt.Color(204, 0, 0));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel25.setText("    Home Page");
        jPanel26.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_manage_student.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel27.setBackground(new java.awt.Color(204, 0, 0));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel26.setText("    Home Page");
        jPanel27.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel28.setBackground(new java.awt.Color(204, 0, 0));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel27.setText("    Home Page");
        jPanel28.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel27.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_manage_student.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel29.setBackground(new java.awt.Color(204, 0, 0));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel28.setText("    Home Page");
        jPanel29.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel30.setBackground(new java.awt.Color(204, 0, 0));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel29.setText("    Home Page");
        jPanel30.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel29.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel31.setBackground(new java.awt.Color(204, 0, 0));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel30.setText("    Home Page");
        jPanel31.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel32.setBackground(new java.awt.Color(204, 0, 0));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel31.setText("    Home Page");
        jPanel32.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel31.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel29.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_manage_student.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_manage_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 30));

        panal_issue.setBackground(new java.awt.Color(0, 0, 0));
        panal_issue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issue.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_issue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-book-32.png"))); // NOI18N
        lbl_issue.setText("Issue Book");
        lbl_issue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_issueMouseClicked(evt);
            }
        });
        panal_issue.add(lbl_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 240, 50));

        jPanel34.setBackground(new java.awt.Color(204, 0, 0));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel33.setText("    Home Page");
        jPanel34.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_issue.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel35.setBackground(new java.awt.Color(204, 0, 0));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel34.setText("    Home Page");
        jPanel35.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel36.setBackground(new java.awt.Color(204, 0, 0));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel35.setText("    Home Page");
        jPanel36.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_issue.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel37.setBackground(new java.awt.Color(204, 0, 0));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel36.setText("    Home Page");
        jPanel37.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel38.setBackground(new java.awt.Color(204, 0, 0));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel37.setText("    Home Page");
        jPanel38.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel39.setBackground(new java.awt.Color(204, 0, 0));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel38.setText("    Home Page");
        jPanel39.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel40.setBackground(new java.awt.Color(204, 0, 0));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel39.setText("    Home Page");
        jPanel40.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel37.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_issue.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 30));

        panal_return.setBackground(new java.awt.Color(0, 0, 0));
        panal_return.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_return.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_return.setForeground(new java.awt.Color(255, 255, 255));
        lbl_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-24.png"))); // NOI18N
        lbl_return.setText("Return Book");
        lbl_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnMouseClicked(evt);
            }
        });
        panal_return.add(lbl_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 230, 50));

        jPanel42.setBackground(new java.awt.Color(204, 0, 0));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel41.setText("    Home Page");
        jPanel42.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_return.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel43.setBackground(new java.awt.Color(204, 0, 0));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel42.setText("    Home Page");
        jPanel43.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel44.setBackground(new java.awt.Color(204, 0, 0));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel43.setText("    Home Page");
        jPanel44.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel43.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_return.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel45.setBackground(new java.awt.Color(204, 0, 0));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel44.setText("    Home Page");
        jPanel45.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel46.setBackground(new java.awt.Color(204, 0, 0));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel45.setText("    Home Page");
        jPanel46.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel45.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel47.setBackground(new java.awt.Color(204, 0, 0));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel46.setText("    Home Page");
        jPanel47.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel48.setBackground(new java.awt.Color(204, 0, 0));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel47.setText("    Home Page");
        jPanel48.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel45.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_return.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 30));

        panal_report.setBackground(new java.awt.Color(0, 0, 0));
        panal_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_report.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_report.setForeground(new java.awt.Color(255, 255, 255));
        lbl_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-report-32.png"))); // NOI18N
        lbl_report.setText("Report");
        lbl_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reportMouseClicked(evt);
            }
        });
        panal_report.add(lbl_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 230, 50));

        jPanel50.setBackground(new java.awt.Color(204, 0, 0));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel49.setText("    Home Page");
        jPanel50.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_report.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel51.setBackground(new java.awt.Color(204, 0, 0));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel50.setText("    Home Page");
        jPanel51.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel52.setBackground(new java.awt.Color(204, 0, 0));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel51.setText("    Home Page");
        jPanel52.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel51.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_report.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel53.setBackground(new java.awt.Color(204, 0, 0));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel52.setText("    Home Page");
        jPanel53.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel54.setBackground(new java.awt.Color(204, 0, 0));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel53.setText("    Home Page");
        jPanel54.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel55.setBackground(new java.awt.Color(204, 0, 0));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel54.setText("    Home Page");
        jPanel55.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel56.setBackground(new java.awt.Color(204, 0, 0));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel55.setText("    Home Page");
        jPanel56.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel55.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel53.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_report.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 30));

        panal_view_issue.setBackground(new java.awt.Color(0, 0, 0));
        panal_view_issue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_view_issue.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_view_issue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_view_issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-view-24.png"))); // NOI18N
        lbl_view_issue.setText("View Issued Book");
        panal_view_issue.add(lbl_view_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 230, 50));

        jPanel58.setBackground(new java.awt.Color(204, 0, 0));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel57.setText("    Home Page");
        jPanel58.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_view_issue.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel59.setBackground(new java.awt.Color(204, 0, 0));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel58.setText("    Home Page");
        jPanel59.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel60.setBackground(new java.awt.Color(204, 0, 0));
        jPanel60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel59.setText("    Home Page");
        jPanel60.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel59.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_view_issue.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel61.setBackground(new java.awt.Color(204, 0, 0));
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel60.setText("    Home Page");
        jPanel61.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel62.setBackground(new java.awt.Color(204, 0, 0));
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel61.setText("    Home Page");
        jPanel62.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel61.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel63.setBackground(new java.awt.Color(204, 0, 0));
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel62.setText("    Home Page");
        jPanel63.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel64.setBackground(new java.awt.Color(204, 0, 0));
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel63.setText("    Home Page");
        jPanel64.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel63.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel61.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_view_issue.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_view_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 30));

        panal_logout.setBackground(new java.awt.Color(102, 102, 255));
        panal_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-log-out-24.png"))); // NOI18N
        lbl_logout.setText("Logout");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        panal_logout.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 240, 50));

        jPanel74.setBackground(new java.awt.Color(204, 0, 0));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel73.setText("    Home Page");
        jPanel74.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        panal_logout.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel75.setBackground(new java.awt.Color(204, 0, 0));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel74.setText("    Home Page");
        jPanel75.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel76.setBackground(new java.awt.Color(204, 0, 0));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel75.setText("    Home Page");
        jPanel76.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel75.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_logout.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel77.setBackground(new java.awt.Color(204, 0, 0));
        jPanel77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel76.setText("    Home Page");
        jPanel77.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel78.setBackground(new java.awt.Color(204, 0, 0));
        jPanel78.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel77.setText("    Home Page");
        jPanel78.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel77.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel79.setBackground(new java.awt.Color(204, 0, 0));
        jPanel79.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel78.setText("    Home Page");
        jPanel79.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel80.setBackground(new java.awt.Color(204, 0, 0));
        jPanel80.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel79.setText("    Home Page");
        jPanel80.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jPanel79.add(jPanel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        jPanel77.add(jPanel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        panal_logout.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 30));

        jPanel4.add(panal_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 600));

        jPanel81.setBackground(new java.awt.Color(255, 255, 255));
        jPanel81.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel82.setBackground(new java.awt.Color(204, 255, 255));
        jPanel82.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(0, 102, 0)));
        jPanel82.setForeground(new java.awt.Color(0, 0, 0));
        jPanel82.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 0, 0));
        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-60.png"))); // NOI18N
        jLabel80.setText("           ");
        jPanel82.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        lbl_student.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_student.setForeground(new java.awt.Color(0, 0, 0));
        lbl_student.setText("10");
        jPanel82.add(lbl_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, 30));

        jPanel81.add(jPanel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 250, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No Of Students");
        jPanel81.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jPanel83.setBackground(new java.awt.Color(255, 153, 153));
        jPanel83.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 0, 51)));
        jPanel83.setForeground(new java.awt.Color(0, 0, 0));
        jPanel83.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-book-stack-60.png"))); // NOI18N
        jLabel82.setText("           ");
        jPanel83.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        lbl_books_no.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_books_no.setForeground(new java.awt.Color(0, 0, 0));
        lbl_books_no.setText("10");
        jPanel83.add(lbl_books_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jPanel81.add(jPanel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 250, 120));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 0, 0));
        jLabel84.setText("No Of Books");
        jPanel81.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jPanel84.setBackground(new java.awt.Color(0, 153, 153));
        jPanel84.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 0, 51)));
        jPanel84.setForeground(new java.awt.Color(0, 0, 0));
        jPanel84.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-knowledge-sharing-60.png"))); // NOI18N
        jLabel85.setText("           ");
        jPanel84.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        lbl_no_bookissue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_no_bookissue.setForeground(new java.awt.Color(0, 0, 0));
        lbl_no_bookissue.setText("10");
        jPanel84.add(lbl_no_bookissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jPanel81.add(jPanel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 250, 120));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(0, 0, 0));
        jLabel87.setText("No Of Book Issues");
        jPanel81.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jPanel85.setBackground(new java.awt.Color(255, 255, 102));
        jPanel85.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 102, 51)));
        jPanel85.setForeground(new java.awt.Color(0, 0, 0));
        jPanel85.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 0, 0));
        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-remove-book-60.png"))); // NOI18N
        jLabel88.setText("           ");
        jPanel85.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        lbl_no_of_books_toreturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_no_of_books_toreturn.setForeground(new java.awt.Color(0, 0, 0));
        lbl_no_of_books_toreturn.setText("10");
        jPanel85.add(lbl_no_of_books_toreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jPanel81.add(jPanel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 250, 120));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(0, 0, 0));
        jLabel90.setText("No Of  Books To Return ");
        jPanel81.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jPanel1.add(jPanel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 860, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -4, 1160, 660));

        setSize(new java.awt.Dimension(1178, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_manage_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manage_bookMouseClicked
       VManageBook MB=new VManageBook();
       MB.setVisible(true);
       dispose();
    }//GEN-LAST:event_lbl_manage_bookMouseClicked

    private void lbl_issueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueMouseClicked
        // TODO add your handling code here:
        VIssueBook IS=new VIssueBook();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_issueMouseClicked

    private void lbl_manage_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manage_studentsMouseClicked
        VManageStudent MB=new VManageStudent();
        MB.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manage_studentsMouseClicked

    private void lbl_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnMouseClicked
       new VReturnBook().setVisible(true);
       dispose();
    }//GEN-LAST:event_lbl_returnMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        new VLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reportMouseClicked
        // TODO add your handling code here:
        new VReport().setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_reportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_books_no;
    private javax.swing.JLabel lbl_issue;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_manage_book;
    private javax.swing.JLabel lbl_manage_students;
    private javax.swing.JLabel lbl_no_bookissue;
    private javax.swing.JLabel lbl_no_of_books_toreturn;
    private javax.swing.JLabel lbl_report;
    private javax.swing.JLabel lbl_return;
    private javax.swing.JLabel lbl_student;
    private javax.swing.JLabel lbl_view_issue;
    private javax.swing.JLabel lbl_view_return;
    private javax.swing.JPanel panal_issue;
    private javax.swing.JPanel panal_logout;
    private javax.swing.JPanel panal_manage_student;
    private javax.swing.JPanel panal_managebook;
    private javax.swing.JPanel panal_report;
    private javax.swing.JPanel panal_return;
    private javax.swing.JPanel panal_view_issue;
    private javax.swing.JPanel panal_view_return;
    // End of variables declaration//GEN-END:variables
}
