/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author HP
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_password = new javax.swing.JLabel();
        lbl_username2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        btn_close = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_password.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setText("Password");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 120, 30));

        lbl_username2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_username2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_username2.setText("User Name");
        getContentPane().add(lbl_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, 30));

        txt_username.setBackground(new java.awt.Color(204, 204, 255));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 190, 30));

        pf_password.setBackground(new java.awt.Color(204, 204, 255));
        pf_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pf_password.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 190, -1));

        btn_close.setBackground(new java.awt.Color(204, 204, 255));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_close.setForeground(new java.awt.Color(0, 0, 0));
        btn_close.setText("Close");
        btn_close.setBorder(null);
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 129, 43));

        btn_login.setBackground(new java.awt.Color(204, 204, 255));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 145, 43));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books_library_shelves_138556_1366x768.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setRequestFocusEnabled(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if(txt_username.getText().equals("nuskan")&& pf_password.getText().equals("123")){
        VHome home=new VHome();
       home.setVisible(true);
       dispose();
        }
        else{
             JOptionPane.showMessageDialog(null, "incorrect user name or password");

        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username2;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
