/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DatabaseCon;

/**
 *
 * @author HP
 */
public class VManageStudent extends javax.swing.JFrame {

    /**
     * Creates new form VManageBook
     */
    public VManageStudent() {
        initComponents();
        setStudenttable();
        incrementBookID();
        
    }
    int studentid;
    String name,fname,course,branch,year,sem;
    DefaultTableModel model;
    private static Connection con;
    public void setStudenttable(){
        try {
            String path = "jdbc:mysql://localhost/library_management";
            con=DriverManager.getConnection(path, "root", "");
            //Statement st= DatabaseCon.createDBConnection().createStatement();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select*from student");
            
            while (rs.next()) {
                int studentid = rs.getInt("student_id");
                String name=rs.getString("name");
                String fname=rs.getString("fathers_name");
                String course=rs.getString("course");
                String branch=rs.getString("branch");
                String year=rs.getString("year");
                String sem=rs.getString("semister");
                
                Object[] obj ={studentid,name,fname,course,branch,year,sem};
                model=(DefaultTableModel)table_manage_Student.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void clearTable(){
        DefaultTableModel model=(DefaultTableModel) table_manage_Student.getModel();
        model.setRowCount(0);
    }
    private void incrementBookID() {
        try {
            //Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/library_management", "root", "");
            Connection con=DatabaseCon.createDBConnection();
            // Query the database to get the next book ID
            String query = "SELECT MAX(student_id) + 1 FROM student";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                int nextstudentId = resultSet.getInt(1);
                //nextBookId++;
                lbl_studentid.setText(Integer.toString(nextstudentId));
            }

            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    public boolean addStudent(){
        boolean isAdded=false;
        //book_id=Integer.parseInt(lbl_bid.getText());
        name=txt_sname.getText();
        fname=txt_f_name.getText();
        course=cmb_course.getSelectedItem().toString();
        branch=cmb_branch.getSelectedItem().toString();
        year=cmb_year.getSelectedItem().toString();
        sem=cmb_sem.getSelectedItem().toString();
        
        try {
            Connection con=DatabaseCon.createDBConnection();
            //String quary="insert into book values(?,?,?,?,?,?)";
            //PreparedStatement pst=con.prepareStatement(quary);
            String query = "INSERT INTO student (name,fathers_name,course,branch,year,semister) VALUES (?, ?, ?, ?, ?,?)";
            PreparedStatement pst = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            //pst.setInt(1, book_id);
            pst.setString(1, name);
            pst.setString(2, fname);
            pst.setString(3, course);
            pst.setString(4, branch);
            pst.setString(5, year);
            pst.setString(6, sem);
            int rowCount=pst.executeUpdate();
            if(rowCount>0){
                ResultSet generatedKeys = pst.getGeneratedKeys();
            if (generatedKeys.next()) {
                studentid = generatedKeys.getInt(1);
                lbl_studentid.setText(Integer.toString(studentid)); // Update the label with the generated book ID
            }
                isAdded=true;
            }
            else{
                isAdded=false;
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isAdded;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_bid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_bname = new javax.swing.JLabel();
        txt_sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_b_edition = new javax.swing.JLabel();
        txt_f_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_publisher = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        lbl_stock1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_sem = new javax.swing.JComboBox<>();
        cmb_course = new javax.swing.JComboBox<>();
        cmb_branch = new javax.swing.JComboBox<>();
        cmb_year = new javax.swing.JComboBox<>();
        lbl_studentid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_manage_Student = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setBackground(new java.awt.Color(102, 102, 255));
        btn_back.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_back.setText("<< Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Manage Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, 30));

        lbl_bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_bid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bid.setText("Student ID");
        jPanel1.add(lbl_bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-book-stack-60.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-address-book-50.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 50));

        lbl_bname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_bname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bname.setText("Student Name");
        jPanel1.add(lbl_bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        txt_sname.setBackground(new java.awt.Color(255, 51, 51));
        txt_sname.setForeground(new java.awt.Color(0, 102, 102));
        txt_sname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 240, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-versions-48.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 50));

        lbl_b_edition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_b_edition.setForeground(new java.awt.Color(255, 255, 255));
        lbl_b_edition.setText("Fathers Name");
        jPanel1.add(lbl_b_edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        txt_f_name.setBackground(new java.awt.Color(255, 51, 51));
        txt_f_name.setForeground(new java.awt.Color(0, 102, 102));
        txt_f_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-hunt-60.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 60, 50));

        lbl_publisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_publisher.setForeground(new java.awt.Color(255, 255, 255));
        lbl_publisher.setText("Course");
        jPanel1.add(lbl_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-price-50.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 60, 50));

        lbl_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("Branch");
        jPanel1.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-stock-48.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 60, 50));

        lbl_stock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_stock.setForeground(new java.awt.Color(255, 255, 255));
        lbl_stock.setText("Year");
        jPanel1.add(lbl_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        btn_delete.setBackground(new java.awt.Color(102, 102, 255));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 80, 30));

        btn_add.setBackground(new java.awt.Color(102, 102, 255));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 90, 30));

        btn_update.setBackground(new java.awt.Color(102, 102, 255));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 80, 30));

        lbl_stock1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_stock1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_stock1.setText("Semester");
        jPanel1.add(lbl_stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-stock-48.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 60, 50));

        cmb_sem.setBackground(new java.awt.Color(255, 51, 51));
        cmb_sem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_sem.setForeground(new java.awt.Color(0, 0, 0));
        cmb_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 st Sem", "2 nd Sem", "3 rd Sem", "4 th Sem", "5 th Sem", "6 th Sem", "7 th Sem", "8 th Sem" }));
        cmb_sem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmb_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 240, 30));

        cmb_course.setBackground(new java.awt.Color(255, 51, 51));
        cmb_course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_course.setForeground(new java.awt.Color(0, 0, 0));
        cmb_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bse", "DNE", "DSE", "Logistic", "HR" }));
        cmb_course.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmb_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 336, 240, 30));

        cmb_branch.setBackground(new java.awt.Color(255, 51, 51));
        cmb_branch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_branch.setForeground(new java.awt.Color(0, 0, 0));
        cmb_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombo", "Kandy", "Galle" }));
        cmb_branch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmb_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 240, 30));

        cmb_year.setBackground(new java.awt.Color(255, 51, 51));
        cmb_year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_year.setForeground(new java.awt.Color(0, 0, 0));
        cmb_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 st", "2 nd", "3 rd", "4 th" }));
        cmb_year.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 240, 30));

        lbl_studentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_studentid.setForeground(new java.awt.Color(0, 0, 0));
        lbl_studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 690));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_manage_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student Name", "F Name", "Course", "Branch", "Year", "Sem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_manage_Student);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 690, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 690, 690));

        setSize(new java.awt.Dimension(1103, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
       VHome home=new VHome();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(addStudent()==true){
            JOptionPane.showMessageDialog(this, "book added succesfully");
            clearTable();
            setStudenttable();
        }
        else{
            JOptionPane.showMessageDialog(this, "book not added");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_branch;
    private javax.swing.JComboBox<String> cmb_course;
    private javax.swing.JComboBox<String> cmb_sem;
    private javax.swing.JComboBox<String> cmb_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_b_edition;
    private javax.swing.JLabel lbl_bid;
    private javax.swing.JLabel lbl_bname;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_publisher;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_stock1;
    private javax.swing.JLabel lbl_studentid;
    private rojeru_san.complementos.RSTableMetro table_manage_Student;
    private javax.swing.JTextField txt_f_name;
    private javax.swing.JTextField txt_sname;
    // End of variables declaration//GEN-END:variables
}
